# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MoviesRPC.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fMoviesRPC.proto\"\x86\x02\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04plot\x18\x02 \x01(\t\x12\x0e\n\x06genres\x18\x03 \x03(\t\x12\x0f\n\x07runtime\x18\x04 \x01(\x05\x12\x0c\n\x04\x63\x61st\x18\x05 \x03(\t\x12\x1a\n\x12num_mflix_comments\x18\x06 \x01(\x05\x12\r\n\x05title\x18\x07 \x01(\t\x12\x10\n\x08\x66ullplot\x18\x08 \x01(\t\x12\x11\n\tlanguages\x18\t \x03(\t\x12\x11\n\tdirectors\x18\n \x03(\t\x12\r\n\x05rated\x18\x0b \x01(\t\x12\x13\n\x0blastupdated\x18\x0c \x01(\t\x12\x0c\n\x04year\x18\r \x01(\x03\x12\x11\n\tcountries\x18\x0e \x03(\t\x12\x0c\n\x04type\x18\x0f \x01(\t\"\x1e\n\tMovieName\x12\x11\n\tnameMovie\x18\x01 \x01(\t\"\x1e\n\x0cMovieFilters\x12\x0e\n\x06values\x18\x01 \x03(\t\"Z\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\x05movie\x18\x03 \x01(\x0b\x32\x06.Movie\x12\x16\n\x06movies\x18\x04 \x03(\x0b\x32\x06.Movie\"P\n\x07Request\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x15\n\x05movie\x18\x02 \x01(\x0b\x32\x06.Movie\x12\x1e\n\x07\x66ilters\x18\x03 \x01(\x0b\x32\r.MovieFilters2\x86\x02\n\x0cMovieMethods\x12\"\n\x0b\x43reateMovie\x12\x06.Movie\x1a\t.Response\"\x00\x12#\n\x08GetMovie\x12\n.MovieName\x1a\t.Response\"\x00\x12.\n\x10GetMoviesByActor\x12\r.MovieFilters\x1a\t.Response\"\x00\x12\x31\n\x13GetMoviesByCategory\x12\r.MovieFilters\x1a\t.Response\"\x00\x12\"\n\x0bUpdateMovie\x12\x06.Movie\x1a\t.Response\"\x00\x12&\n\x0b\x44\x65leteMovie\x12\n.MovieName\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MoviesRPC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MOVIE']._serialized_start=20
  _globals['_MOVIE']._serialized_end=282
  _globals['_MOVIENAME']._serialized_start=284
  _globals['_MOVIENAME']._serialized_end=314
  _globals['_MOVIEFILTERS']._serialized_start=316
  _globals['_MOVIEFILTERS']._serialized_end=346
  _globals['_RESPONSE']._serialized_start=348
  _globals['_RESPONSE']._serialized_end=438
  _globals['_REQUEST']._serialized_start=440
  _globals['_REQUEST']._serialized_end=520
  _globals['_MOVIEMETHODS']._serialized_start=523
  _globals['_MOVIEMETHODS']._serialized_end=785
# @@protoc_insertion_point(module_scope)
