# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Movies.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cMovies.proto\"2\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06genres\x18\x03 \x03(\t\".\n\x0cMovieFilters\x12\x0e\n\x06\x63olumn\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\t\"Z\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\x05movie\x18\x03 \x01(\x0b\x32\x06.Movie\x12\x16\n\x06movies\x18\x04 \x03(\x0b\x32\x06.Movie\"P\n\x07Request\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x15\n\x05movie\x18\x02 \x01(\x0b\x32\x06.Movie\x12\x1e\n\x07\x66ilters\x18\x03 \x01(\x0b\x32\r.MovieFiltersb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Movies_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MOVIE']._serialized_start=16
  _globals['_MOVIE']._serialized_end=66
  _globals['_MOVIEFILTERS']._serialized_start=68
  _globals['_MOVIEFILTERS']._serialized_end=114
  _globals['_RESPONSE']._serialized_start=116
  _globals['_RESPONSE']._serialized_end=206
  _globals['_REQUEST']._serialized_start=208
  _globals['_REQUEST']._serialized_end=288
# @@protoc_insertion_point(module_scope)
